name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: [self-hosted, pod]
    steps:
      - name: Set up Docker Buildx
        run: sudo wget -O /home/runner/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.24.0/buildx-v0.24.0.linux-amd64

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: ${{ secrets.HARBOR_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_PUSH_TOKEN }}

      - name: Build and push latest image
        run: docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build default
  
  build-multi:
    runs-on: [self-hosted, pod]
    steps:
      - name: Set up Docker Buildx
        run: sudo wget -O /home/runner/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.24.0/buildx-v0.24.0.linux-amd64

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: robot$action-runner+build-ci
          password: ${{ secrets.HARBOR_ACTION_RUNNER_PUSH_TOKEN }}

      - name: Build and push latest image
        run: docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build multi
