name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, pod]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.24.0

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: ${{ secrets.HARBOR_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_PUSH_TOKEN }}

      - name: Build and push latest image
        run: docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build default

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: robot$action-runner+build-ci
          password: ${{ secrets.HARBOR_ACTION_RUNNER_PUSH_TOKEN }}

      - name: Build and push latest image
        run: docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build multi
