name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: [self-hosted, pod]
    steps:
      - name: Set up Docker Buildx
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: 10
          polling_interval_seconds: 20
          command: |
            sudo wget -O /home/runner/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.24.0/buildx-v0.24.0.linux-amd64

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: ${{ secrets.HARBOR_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_PUSH_TOKEN }}

      - name: Build and push latest image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 360
          max_attempts: 10
          polling_interval_seconds: 20
          command: |
            docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build default
  
  build-multi:
    runs-on: [self-hosted, pod]
    strategy:
      fail-fast: false
      matrix:
        distos: ["openeuler", "tencentos", "centos"]
    steps:
      - name: Set up Docker Buildx
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: 10
          polling_interval_seconds: 20
          command: |
            sudo wget -O /home/runner/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.24.0/buildx-v0.24.0.linux-amd64

      - name: Login registry.smtx.io
        uses: docker/login-action@v2
        with:
          registry: registry.smtx.io
          username: robot$action-runner+build-ci
          password: ${{ secrets.HARBOR_ACTION_RUNNER_PUSH_TOKEN }}

      - name: Build and push latest image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 360
          max_attempts: 10
          polling_interval_seconds: 20
          command: |
            docker buildx bake "https://github.com/everoute/actions-runner-controller.git#main" --call build ${{ matrix.distos }}
